#!/usr/bin/env python3

# from __future__ import print_function

import sys
import os
import tempfile
import shutil
import configparser
import argparse
import re
import urllib.request
import subprocess


def copy_tpl(src, dst, values):
    with open(src, 'r') as src_fp:
        data = src_fp.read()
        data = data.format(**values)
        with open(dst, 'w') as dst_fp:
            dst_fp.write(data)

parser = argparse.ArgumentParser(description='Download Thunderbird binaries and repack them into a deb-package.')
parser.add_argument('--channel', dest='channel', default='release', help='Release channel, beta or release, default is release [BETA IS NOT AVAILABLE NOW]')
args = parser.parse_args()

if args.channel not in ('release', ):
    print('Unknown channel: %s' % args.channel)
    sys.exit(1)

if args.channel == 'beta':
    # not supported actually
    ARCHIVE_URL = 'https://download.mozilla.org/?product=thunderbird-latest-SSL&os=linux64&lang=en-US'
elif args.channel == 'release':
    ARCHIVE_URL = 'https://download.mozilla.org/?product=thunderbird-latest-SSL&os=linux64&lang=en-US'

# prepare files and dirs
START_DIR = os.getcwd()
BUILD_DIR = tempfile.mkdtemp()
ARCHIVE_NAME = os.path.join(BUILD_DIR, 'archive.tmp')

def cleanup():
    shutil.rmtree(BUILD_DIR)

print('Downloading archive...')
(archive_file, _hmo) = urllib.request.urlretrieve(ARCHIVE_URL, ARCHIVE_NAME)

os.chdir(BUILD_DIR)

print('Unpacking archive...')
subprocess.call(['tar', 'xf', archive_file])

COMPACT_VERSION = re.compile('^[0-9]+\\.[0-9]+$')

src_dir = os.path.join(BUILD_DIR, 'thunderbird')

tmp_dir = tempfile.mkdtemp()
# print(tmp_dir)

if not os.path.isdir(src_dir):
    print('{0} is not a directory!'.format(src_dir))
    sys.exit(1)

# read application.ini
src_app_config = configparser.ConfigParser()
try:
    src_app_config.read_file(open(os.path.join(src_dir, 'application.ini')))
    app_version = src_app_config.get('App', 'Version')
    app_build = src_app_config.get('App', 'BuildID')
except Exception as e:
    print('Failed to read application.ini: {0}'.format(str(e)))
    cleanup()
    sys.exit(1)

if COMPACT_VERSION.match(app_version) is not None:
    app_version += '.0'

full_version = '{0}.{1}'.format(app_version, app_build)
print('Detected version {0}'.format(full_version))

pkg_dst = os.path.join(tmp_dir, 'package.dir')
debian_dst = os.path.join(pkg_dst, 'DEBIAN')
os.makedirs(debian_dst)

for d in ['usr/lib/thunderbird', 'usr/share/pixmaps', 'usr/share/applications', 'usr/bin']:
    os.makedirs(os.path.join(pkg_dst, d))

copy_tpl(os.path.join(START_DIR, 'debian-tpl', 'control'), os.path.join(debian_dst, 'control'), {'version':full_version})

# copy other files
dst_usr = os.path.join(pkg_dst, 'usr/lib/thunderbird')
for f in os.listdir(src_dir):
    p = os.path.join(src_dir, f)
    if os.path.isfile(p):
        shutil.copy(p, dst_usr)
    elif os.path.isdir(p):
        if f == 'dictionaries':
            os.symlink('../../share/hunspell', os.path.join(dst_usr, f))
        else:
            shutil.copytree(p, os.path.join(dst_usr, f))

# icons and other resources
shutil.copy(os.path.join(START_DIR, 'debian-tpl', 'thunderbird.png'), os.path.join(pkg_dst, 'usr/share/pixmaps'))
shutil.copy(os.path.join(START_DIR, 'debian-tpl', 'thunderbird.desktop'), os.path.join(pkg_dst, 'usr/share/applications'))

os.symlink('../lib/thunderbird/thunderbird', os.path.join(pkg_dst, 'usr/bin/thunderbird'))

cmd = ['fakeroot', '/usr/bin/dpkg', '-b', os.path.join(tmp_dir, 'package.dir'), tmp_dir]
subprocess.call(cmd)

deb_pkg = False

for f in os.listdir(tmp_dir):
    if f.endswith('.deb'):
        shutil.copy(os.path.join(tmp_dir,f), START_DIR)
        print('File {0} successfully copied to local directory.'.format(f))

cleanup()


